### ISSUE TITLE
Not an issue but need help.

### ISSUE THREAD

**Issue by roubochr** [reesvarney/acc-server-browser-web#10]
I'm so excited to get this up and running and really appreciate what you've created! Im currently trying to find the auth certs in wireshark but cant seen to find the packets you're referring to. I have the TCP stream and can see all the server data and ip's but cant seem to find the specific [FIN] packets. 
Any help would be appreciated! 
Thanks

**Comment by reesvarney** [comment]
Hi, sorry its taken me a while to get back to you, I've been busy with exams. 

I'm not 100% sure but I'd recommend checking some of your wireshark options especially around websockets - unfortunately I still don't have access to the PC I used to originally get the packets for another couple weeks but if you still can't find them I will have a better look then.

Also you could look more generally at the outgoing packets to the kunos server. The payload for the auth string should look like a string of hex separated by "|" characters and the query string when converted to ASCII should appear as a set of IP addresses with region names and some extra unknown characters.
